core/urls.py
from django.db.models.query import create_namedtuple_class
from django.urls import include, path

from core.views import (
    CounterPartyCreateView,
    CreateProduct,
    CreateTrade,
    ListCounterParties,
    ListProducts,
    ListTrades,
    add_counter_party,
)

app_name = "core"
urlpatterns = [
    path("create_trade/", CreateTrade.as_view(), name="createtrade"),
    path(
        "create_counterparty/",
        CounterPartyCreateView.as_view(),
        name="createcounterparty",
    ),
    path("create_product/", CreateProduct.as_view(), name="createproduct"),
    path("list_trade/", ListProducts.as_view(), name="listproducts"),
    path("list_product/", ListTrades.as_view(), name="listtrades"),
    path("list_counterparty/", ListCounterParties.as_view(), name="listcounterparty"),
    path("add-counterparty/", add_counter_party, name="add-counterparty"),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import include, path

from core.views import FrontPage

urlpatterns = [
    path("admin/", admin.site.urls),
    path("core/", include("core.urls")),
    path("", FrontPage.as_view(), name="frontpage"),
]

core/models.py
from django.db import models


class Product(models.Model):
    description = models.CharField(max_length=50)

    class ProductClass(models.TextChoices):
        Bond = "Bond", "Bond"
        Equity = "Equity", "Equity"
        Interst = "Interst", "Interest"
        Forex = "Forex", "Forex"
        Commodities = "Commodities", "Commodities"

    class ProductType(models.TextChoices):
        Option = "Option", "Option"
        Forward = "Forward", "Forward"
        Future = "Future", "Future"
        Swap = "Swap", "Swap"
        SwapCrossCurrency = "SwapCrossCurrency", "SwapCrossCurrency"
        Spot = "Spot", "Spot"
        Standard = "Standard", "Standard"

    product_type = models.CharField(
        max_length=20, choices=ProductType.choices, default=ProductType.Standard
    )

    product_class = models.CharField(
        max_length=20, choices=ProductClass.choices, default=ProductClass.Bond
    )

    def __str__(self):
        return (
            f"{self.id}, {self.product_type} , {self.product_class}, {self.description}"
        )


class CounterParty(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.name}"


class TradingBook(models.Model):
    name = models.CharField(max_length=50, default="book")

    def __str__(self):
        return f"{self.name}"


# Create your models here.
class Trade(models.Model):
    counterparty = models.ForeignKey(CounterParty, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    tradingbook = models.ForeignKey(TradingBook, on_delete=models.CASCADE)

    price = models.FloatField()
    quantity = models.IntegerField()

    def __str__(self):
        return f"{self.id}, {self.product} , {self.quantity}, {self.price}"

core/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, TemplateView, CreateView
from .models import Product, Trade, CounterParty


class FrontPage(TemplateView):
    template_name = "core/frontpage.html"


class CounterPartyCreateView(CreateView):
    model = CounterParty
    template_name = "core/createcounterparty.html"
    success_url = reverse_lazy("frontpage")
    fields = ["name"]


class CreateTrade(CreateView):
    model = Trade
    template_name = "core/createtrade.html"
    success_url = reverse_lazy("frontpage")
    fields = ["counterparty", "product", "price", "quantity", "tradingbook"]


class CreateProduct(CreateView):
    model = Product
    template_name = "core/createproduct.html"
    success_url = reverse_lazy("frontpage")
    fields = ["product_type", "product_class", "description"]


class ListTrades(ListView):
    model = Trade
    template_name = "core/listtrades.html"


class ListProducts(ListView):
    model = Product
    template_name = "core/listproducts.html"


class ListCounterParties(ListView):
    model = CounterParty
    template_name = "core/listcounterparties.html"
    context_object_name = "parties"


def add_counter_party(request):
    name = request.POST.get("counterparty")
    CounterParty.objects.create(name=name)
    parties = CounterParty.objects.all()
    return render(request, "partials/counterparty-list.html", {"parties": parties})

core/templates/core/base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title></title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
    <script src="https://unpkg.com/htmx.org@2.0.3" integrity="sha384-0895/pl2MU10Hqc6jd4RvrthNlDiE9U1tWmX7WRESftEDRosgxNsQG/Ze9YMRzHq" crossorigin="anonymous"></script>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'frontpage' %}">TradeApp</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link" href="{% url 'core:createtrade' %}">Add Trade</a>
          <a class="nav-link" href="{% url 'core:listtrades' %}">List Trades</a>
          <a class="nav-link" href="#">View Item</a>
        </div>
      </div>
    </div>
  </nav>
  {% block body %}
  {% endblock %}
</body>

</html>

core/templates/core/createcounterparty.html
{% extends 'core/base.html' %}
{% block body %}

<h1>Create a Product</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
{% endblock %}

core/templates/core/createproduct.html
{% extends 'core/base.html' %}
{% block body %}

<h1>Create a Product</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
{% endblock %}

core/templates/core/createtrade.html
{% extends 'core/base.html' %}
{% block body %}

<h1>Create a Trade</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
{% endblock %}

core/templates/core/frontpage.html
{% extends 'core/base.html' %}
{% block body %}

<h1>hello world</h1>
<p>hello again</p>
<p><a href="{% url 'core:createtrade' %}">create trade</a></p>
<p><a href="{% url 'core:createcounterparty' %}">create counterparty</a></p>
<p><a href="{% url 'core:createproduct' %}">create product</a></p>
<p><a href="{% url 'core:listtrades' %}">list trade</a></p>
<p><a href="{% url 'core:listproducts' %}">list product</a></p>
<p><a href="{% url 'core:listcounterparty' %}">list counterparty</a></p>

{% endblock %}

core/templates/core/listcounterparties.html
{% extends 'core/base.html' %}
{% block body %}
<h1>ListView</h1>
<div class="align-center col-10 offset-1">
    <div class="d-flex justify-content-between align-items-center">
        <p class="lead ml-0">CounterParties</p>
        <form hx-post="{% url 'core:add-counterparty' %}" hx-target='#cpty-list' class="d-flex align-items-center">
            {% csrf_token %}
            <input type="text" name="counterparty" class="form-control-sm mr-2" placeholder="Enter a counterparty" />
            <button type="submit" class="btn btn-success btn-sm">add counterparty</button>
        </form>
    </div>
    <hr/>
<div id="cpty-list">
  {% include 'partials/counterparty-list.html' %}
</div>
{% endblock %}

core/templates/core/listproducts.html
{% extends 'core/base.html' %}
{% block body %}
<h1>ListView</h1>

{% for product in product_list %}
<p>{{ product }}</p>



{% endfor %}
{% endblock %}

core/templates/core/listtrades.html
{% extends 'core/base.html' %}
{% block body %}
<h1>ListView</h1>

{% for trade in trade_list %}
<p>{{ trade }}</p>



{% endfor %}
{% endblock %}

core/templates/partials/counterparty-list.html
{% if parties %}
    <ul>
    {% for party in parties %}
        <li>{{ party.name }}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>You do not have any counterparties in your list</p>
{% endif %}